apiVersion: v1
kind: Namespace
metadata:
  name: proposal
---
apiVersion: v1 
kind: ServiceAccount
metadata:
  name: proposal-sa
  namespace: proposal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proposal-ui
  namespace: proposal 
  labels:
    app: proposal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proposal-ui
  template:
    metadata:
      labels:
       app: proposal-ui
    spec:
      containers:
        - name: proposal-ui
          image: akinolawilson/proposal:latest
          imagePullPolicy: Always 
          ports:
            - containerPort: 8000
          env:
            - name: "SUB_PATH"
              value: "" # "/proposal/"  
---
apiVersion: v1
kind: Service
metadata:
  name: proposal-ui
  namespace: proposal 

spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
  selector:
    app: proposal-ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proposal-ui-ingress
  namespace: proposal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true" # enable regex for path matching
spec:
  rules:
    - http:
        paths:
        - path: /proposals(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: proposal-ui
              port:
                number: 80