---
## Pod Monitor
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: model-4fd366b0-pod-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      seldon-deployment-id: model-4fd366b0
  podMetricsEndpoints:
    - port: "http"  # Match the container port name
      path: /prometheus
  namespaceSelector:
    any: true
---
## Service Monitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-4fd366b0-service-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      seldon-deployment-id: model-4fd366b0
  # serviceMonitorNamespaceSelector: {}
  endpoints:
  - port: http 
    path: /prometheus 
---
## Seldon Deployment
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: model-4fd366b0
  namespace: models
  annotations:
    seldon.io/no-storage-initializer: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/prometheus"
    prometheus.io/port: "9000"  # Updated to match new container port
spec:
  protocol: v2
  predictors:
    - name: predictor-4fd366b0
      replicas: 1
      graph:
        name: model-4fd366b0
        type: MODEL
        children: []
        implementation: 4FD366B0_SERVER
      svcOrchSpec:
        env:
          - name: LOG_LEVEL
            value: DEBUG
          - name: ROOT_PATH
            value: "/4fd366b0"
          - name: PREDICTIVE_UNIT_METRICS_SERVICE_PORT
            value: "9000"
          - name: PREDICTIVE_UNIT_METRICS_ENDPOINT
            value: "/prometheus"
      componentSpecs:
        - spec:
            containers:
              - name: model-4fd366b0
                env:
                  - name: ROOT_PATH
                    value: "/4fd366b0"
                  - name: UVICORN_FORWARDED_ALLOW_IPS
                    value: "*"
                  - name: MLSERVER_METRICS_PORT
                    value: "9000"
                  - name: MLSERVER_METRICS_ENDPOINT
                    value: "/prometheus"
                livenessProbe:
                  httpGet:
                    path: /v2/health/live
                    port: http  # Named port reference
                  initialDelaySeconds: 20
                  periodSeconds: 10
                readinessProbe:
                  httpGet:
                    path: /v2/health/ready
                    port: http  # Named port reference
                  initialDelaySeconds: 20
                  periodSeconds: 10
                ports:
                  - name: http  # Updated from "metrics" to "http"
                    containerPort: 9000
                    protocol: TCP
                resources:
                  requests:
                    memory: "512Mi"
                    cpu: "500m"
                    nvidia.com/gpu: "1"
                  limits:
                    memory: "20Gi"
                    cpu: "2"
                    nvidia.com/gpu: "1"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-4fd366b0-docs-ingress
  namespace: models
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"  # Enable regex matching
    nginx.ingress.kubernetes.io/rewrite-target: /docs$1$2
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # API Documentation Endpoint
          - path: /4fd366b0/docs(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: model-4fd366b0-predictor-4fd366b0-model-4fd366b0 # seldon-models-model-4fd366b0 ### model-4fd366b0-predictor-4fd366b0-model-4fd366b0
                port:
                  number: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-4fd366b0-api-ingress
  namespace: models
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"  # Enable regex matching
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Prediction Endpoint
          - path: /4fd366b0(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: model-4fd366b0-predictor-4fd366b0-model-4fd366b0  # seldon-models-model-4fd366b0 ### model-4fd366b0-predictor-4fd366b0-model-4fd366b0
                port:
                  number: 9000