apiVersion: v1
kind: ConfigMap
metadata:
  name: seldon-dashboard-4fd366b0
  namespace: monitoring
  labels:
    grafana_dashboard: "1"  # Sidecar will detect this
data:
# http://prometheus.monitoring.svc.cluster.local:9090/prometheus
  4fd366b0-dashboard.json: |
    {
        "uid": "4fd366b0",
        "title": "Seldon Core Metrics",
        "description": "This dashboard tracks key metrics for Seldon Core, including inference requests, system resource usage, and performance.",
        "editable": true,
        "annotations": {
            "list": [
                {
                    "builtIn": 1,
                    "type": "dashboard"
                }
            ]
        },
        "rows": [
            {
                "title": "System Metrics",
                "panels": [
                    {
                        "title": "CPU Usage (%)",
                        "type": "gauge",
                        "datasource": "Prometheus",
                        "gridPos": {
                            "x": 0,
                            "y": 0,
                            "w": 6,
                            "h": 4
                        },
                        "targets": [
                            {
                                "expr": "server_cpu_usage",
                                "legendFormat": "CPU %"
                            }
                        ],
                        "thresholds": {
                            "mode": "absolute",
                            "steps": [
                                {
                                    "value": null,
                                    "color": "green"
                                },
                                {
                                    "value": 80,
                                    "color": "yellow"
                                },
                                {
                                    "value": 90,
                                    "color": "red"
                                }
                            ]
                        },
                        "description": "Current CPU usage as a percentage of total capacity."
                    },
                    {
                        "title": "Memory Usage (GB)",
                        "type": "gauge",
                        "datasource": "Prometheus",
                        "gridPos": {
                            "x": 6,
                            "y": 0,
                            "w": 6,
                            "h": 4
                        },
                        "targets": [
                            {
                                "expr": "server_memory_usage_gigabytes",
                                "legendFormat": "Memory GB"
                            }
                        ],
                        "thresholds": {
                            "mode": "absolute",
                            "steps": [
                                {
                                    "value": null,
                                    "color": "green"
                                },
                                {
                                    "value": 16,
                                    "color": "yellow"
                                },
                                {
                                    "value": 20,
                                    "color": "red"
                                }
                            ]
                        },
                        "description": "Current memory usage in gigabytes."
                    },
                    {
                        "title": "GPU Utilization (%)",
                        "type": "gauge",
                        "datasource": "Prometheus",
                        "gridPos": {
                            "x": 0,
                            "y": 4,
                            "w": 6,
                            "h": 4
                        },
                        "targets": [
                            {
                                "expr": "server_gpu_1_utilization",
                                "legendFormat": "GPU %"
                            }
                        ],
                        "thresholds": {
                            "mode": "absolute",
                            "steps": [
                                {
                                    "value": null,
                                    "color": "green"
                                },
                                {
                                    "value": 70,
                                    "color": "yellow"
                                },
                                {
                                    "value": 90,
                                    "color": "red"
                                }
                            ]
                        },
                        "description": "Current GPU utilization as a percentage of total capacity."
                    },
                    {
                        "title": "GPU Memory Usage (GB)",
                        "type": "gauge",
                        "datasource": "Prometheus",
                        "gridPos": {
                            "x": 6,
                            "y": 4,
                            "w": 6,
                            "h": 4
                        },
                        "targets": [
                            {
                                "expr": "server_gpu_1_memory_usage_gigabytes",
                                "legendFormat": "GPU Mem GB"
                            }
                        ],
                        "thresholds": {
                            "mode": "absolute",
                            "steps": [
                                {
                                    "value": null,
                                    "color": "green"
                                },
                                {
                                    "value": 8,
                                    "color": "yellow"
                                },
                                {
                                    "value": 10,
                                    "color": "red"
                                }
                            ]
                        },
                        "description": "Current GPU memory usage in gigabytes."
                    }
                ]
            },
            {
                "title": "Inference Metrics",
                "panels": [
                    {
                        "title": "Total Inference Requests",
                        "type": "stat",
                        "datasource": "Prometheus",
                        "gridPos": {
                            "x": 0,
                            "y": 8,
                            "w": 4,
                            "h": 3
                        },
                        "targets": [
                            {
                                "expr": "server_requests_total",
                                "legendFormat": "Total Requests"
                            }
                        ],
                        "description": "Total number of inference requests processed."
                    },
                    {
                        "title": "Successful Predictions",
                        "type": "stat",
                        "datasource": "Prometheus",
                        "gridPos": {
                            "x": 4,
                            "y": 8,
                            "w": 4,
                            "h": 3
                        },
                        "targets": [
                            {
                                "expr": "server_successful_predictions_total",
                                "legendFormat": "Success"
                            }
                        ],
                        "description": "Total number of successful predictions."
                    },
                    {
                        "title": "Failed Predictions",
                        "type": "stat",
                        "datasource": "Prometheus",
                        "gridPos": {
                            "x": 8,
                            "y": 8,
                            "w": 4,
                            "h": 3
                        },
                        "targets": [
                            {
                                "expr": "server_failed_predictions_total",
                                "legendFormat": "Failures"
                            }
                        ],
                        "description": "Total number of failed predictions."
                    }
                ]
            },
            {
                "title": "Performance Metrics",
                "panels": [
                    {
                        "title": "Inference Latency",
                        "type": "graph",
                        "datasource": "Prometheus",
                        "gridPos": {
                            "x": 0,
                            "y": 11,
                            "w": 12,
                            "h": 6
                        },
                        "targets": [
                            {
                                "expr": "histogram_quantile(0.95, sum(rate(server_inference_duration_seconds_bucket[5m])) by (le))",
                                "legendFormat": "95th Percentile"
                            }
                        ],
                        "description": "95th percentile inference latency over time."
                    },
                    {
                        "title": "CPU Time Spent (s)",
                        "type": "graph",
                        "datasource": "Prometheus",
                        "gridPos": {
                            "x": 0,
                            "y": 17,
                            "w": 12,
                            "h": 6
                        },
                        "targets": [
                            {
                                "expr": "process_cpu_seconds_total",
                                "legendFormat": "CPU Time"
                            }
                        ],
                        "description": "Total CPU time spent by the process."
                    }
                ]
            },
            {
                "title": "Memory Metrics",
                "panels": [
                    {
                        "title": "Virtual Memory Usage",
                        "type": "stat",
                        "datasource": "Prometheus",
                        "gridPos": {
                            "x": 0,
                            "y": 23,
                            "w": 6,
                            "h": 3
                        },
                        "targets": [
                            {
                                "expr": "process_virtual_memory_bytes / 1e9",
                                "legendFormat": "Virtual Mem (GB)"
                            }
                        ],
                        "description": "Virtual memory usage in gigabytes."
                    },
                    {
                        "title": "Resident Memory Usage",
                        "type": "stat",
                        "datasource": "Prometheus",
                        "gridPos": {
                            "x": 6,
                            "y": 23,
                            "w": 6,
                            "h": 3
                        },
                        "targets": [
                            {
                                "expr": "process_resident_memory_bytes / 1e9",
                                "legendFormat": "Resident Mem (GB)"
                            }
                        ],
                        "description": "Resident memory usage in gigabytes."
                    }
                ]
            },
            {
                "title": "Load Metrics",
                "panels": [
                    {
                        "title": "Model Load Time (s)",
                        "type": "stat",
                        "datasource": "Prometheus",
                        "gridPos": {
                            "x": 0,
                            "y": 26,
                            "w": 6,
                            "h": 3
                        },
                        "targets": [
                            {
                                "expr": "model_load_time_seconds",
                                "legendFormat": "Load Time"
                            }
                        ],
                        "description": "Time taken to load the model."
                    },
                    {
                        "title": "Server Load Time (s)",
                        "type": "stat",
                        "datasource": "Prometheus",
                        "gridPos": {
                            "x": 6,
                            "y": 26,
                            "w": 6,
                            "h": 3
                        },
                        "targets": [
                            {
                                "expr": "server_load_time_seconds",
                                "legendFormat": "Server Load"
                            }
                        ],
                        "description": "Time taken to load the server."
                    }
                ]
            }
        ]
    }




#     {
#       "uid": "4fd366b0",
#       "title": "4fd366b0",
#       "editable": true,
#       "annotations": {
#         "list": [
#           {
#             "builtIn": 1,
#             "type": "dashboard"
#           }
#         ]
#       },
#       "panels": [
#         {
#           "title": "Total Inference Requests",
#           "type": "stat",
#           "datasource": "Prometheus",
#           "targets": [{ "expr": "server_requests_total", "legendFormat": "Total Requests" }]
#         },
#         {
#           "title": "Successful Predictions",
#           "type": "stat",
#           "datasource": "Prometheus",
#           "targets": [{ "expr": "server_successful_predictions_total", "legendFormat": "Success" }]
#         },
#         {
#           "title": "Failed Predictions",
#           "type": "stat",
#           "datasource": "Prometheus",
#           "targets": [{ "expr": "server_failed_predictions_total", "legendFormat": "Failures" }]
#         },
#         {
#           "title": "CPU Usage (%)",
#           "type": "gauge",
#           "datasource": "Prometheus",
#           "targets": [{ "expr": "server_cpu_usage", "legendFormat": "CPU %" }]
#         },
#         {
#           "title": "Memory Usage (GB)",
#           "type": "gauge",
#           "datasource": "Prometheus",
#           "targets": [{ "expr": "server_memory_usage_gigabytes", "legendFormat": "Memory GB" }]
#         },
#         {
#           "title": "GPU Utilization (%)",
#           "type": "gauge",
#           "datasource": "Prometheus",
#           "targets": [{ "expr": "server_gpu_1_utilization", "legendFormat": "GPU %" }]
#         },
#         {
#           "title": "GPU Memory Usage (GB)",
#           "type": "gauge",
#           "datasource": "Prometheus",
#           "targets": [{ "expr": "server_gpu_1_memory_usage_gigabytes", "legendFormat": "GPU Mem GB" }]
#         },
#         {
#           "title": "Inference Latency",
#           "type": "graph",
#           "datasource": "Prometheus",
#           "targets": [
#             { 
#               "expr": "histogram_quantile(0.95, sum(rate(server_inference_duration_seconds_bucket[5m])) by (le))",
#               "legendFormat": "95th Percentile"
#             }
#           ]
#         },
#         {
#           "title": "Virtual Memory Usage",
#           "type": "stat",
#           "datasource": "Prometheus",
#           "targets": [{ "expr": "process_virtual_memory_bytes / 1e9", "legendFormat": "Virtual Mem (GB)" }]
#         },
#         {
#           "title": "Resident Memory Usage",
#           "type": "stat",
#           "datasource": "Prometheus",
#           "targets": [{ "expr": "process_resident_memory_bytes / 1e9", "legendFormat": "Resident Mem (GB)" }]
#         },
#         {
#           "title": "Model Load Time (s)",
#           "type": "stat",
#           "datasource": "Prometheus",
#           "targets": [{ "expr": "model_load_time_seconds", "legendFormat": "Load Time" }]
#         },
#         {
#           "title": "Server Load Time (s)",
#           "type": "stat",
#           "datasource": "Prometheus",
#           "targets": [{ "expr": "server_load_time_seconds", "legendFormat": "Server Load" }]
#         },
#         {
#           "title": "Process Start Time",
#           "type": "stat",
#           "datasource": "Prometheus",
#           "targets": [{ "expr": "process_start_time_seconds", "legendFormat": "Start Time (s)" }]
#         },
#         {
#           "title": "CPU Time Spent (s)",
#           "type": "graph",
#           "datasource": "Prometheus",
#           "targets": [{ "expr": "process_cpu_seconds_total", "legendFormat": "CPU Time" }]
#         }
#       ]
#     }
