apiVersion: v1
kind: Namespace
metadata:
  name: search
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: search-pv
  namespace: search
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/meili  # Local storage on the node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-pvc
  namespace: search
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.7
          ports:
            - containerPort: 7700
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /meili_data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: search-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: search
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7700
  selector:
    app: meilisearch
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: meilisearch-indexer
  namespace: search
spec:
  schedule: "*/2 * * * *" # Run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: indexer
            image: your-indexer-image:latest #build image with katib and grafana indexing scripts
            env:
            - name: MEILISEARCH_HOST
              value: "http://meilisearch.search.svc.cluster.local:7700"
            - name: MEILISEARCH_API_KEY
              value: "your-meilisearch-api-key"
            - name: GRAFANA_URL
              value: "http://grafana.grafana.svc.cluster.local:3000"
            - name: GRAFANA_API_KEY
              value: "your-grafana-api-key"
          restartPolicy: OnFailure
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meilisearch-ingress
  namespace: search
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /search(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: meilisearch
                port:
                  number: 80
