kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# need to replace with env variable below
name: kmlflow-local-v1
nodes:
- role: control-plane
  extraMounts:
      # need to replace with env variable below. 
    - hostPath: /home/ola/Code/kmlflow/volume
      containerPath: /data
- role: worker
- role: worker
- role: worker