apiVersion: v1
kind: ServiceAccount 
metadata:
  name: mlflow-sa 
  namespace: mlflow 
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mlflow-deployment 
  namespace: mlflow 
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow 
  template:
    metadata:
      labels:
        app: mlflow 
    spec:
      serviceAccountName: mlflow-sa

      volumes:
      - name: mlflow-data
        persistentVolumeClaim:
          claimName: mlflow-data # reference the PVC
      containers:
      - name: mlflow
        image: akinolawilson/mlflow:latest
        command: ["/usr/src/app/entrypoint.sh"]
        args: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5001", "--backend-store-uri", "sqlite:///meta.db"]
        imagePullPolicy: Always 
        ports:
          - containerPort: 5001
            
        volumeMounts:
        - name: mlflow-data
          mountPath: /usr/src/app/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data
  namespace: mlflow
spec:
  storageClassName: standard
  volumeName: mlflow-data  # Ensure the volumeName matches the PV name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi