apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-models
  namespace: models
spec:
  predictors:
    - name: default
      replicas: 1
      componentSpecs:
        - spec:
            containers:
              - name: serving-container
                image: akinolawilson/t5-small:e25a09a2
