apiVersion: v1
kind: Namespace
metadata:
  name: gpu-access
---
apiVersion: v1
kind: ServiceAccount 
metadata:
  name: gpu-access-sa
  namespace: gpu-access
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: gpu-access-deployment
  namespace: gpu-access
  labels:
    app: gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu
  template:
    metadata:
      labels:
        app: gpu
    spec:
      serviceAccountName: gpu-access-sa
      containers:
      - name: gpu-acess-test
        image: nvidia/cuda:11.0.3-base-ubuntu20.04
        imagePullPolicy: Always 
        resources:
          limits:
            nvidia.com/gpu: 1 # Request 1 GPU
        command: [ "sleep", "infinity" ] # Keep the container running
