# Generated by Django 5.1.6 on 2025-03-06 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Category Name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tag Subject')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='proposals.category')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_paper_link', models.URLField(blank=True, null=True, verbose_name='Research Paper Link')),
                ('research_paper_title', models.CharField(max_length=200, verbose_name='Research Paper Title')),
                ('title', models.CharField(max_length=200, verbose_name='Proposal Title')),
                ('description', models.TextField(verbose_name='Proposal Description')),
                ('proposal_goal', models.TextField(verbose_name='Proposal Goal')),
                ('trial_runs', models.URLField(blank=True, null=True, verbose_name='Trial Runs Link')),
                ('requested_gpus', models.PositiveIntegerField(verbose_name='Requested GPUs')),
                ('upvotes', models.PositiveIntegerField(default=0, verbose_name='Upvotes')),
                ('expected_compute_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Expected Compute Time (hours)')),
                ('predicted_cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='Predicted Cost (W8S)')),
                ('repo_link', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('tags', models.ManyToManyField(blank=True, related_name='proposals', to='proposals.tags', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'proposali',
                'db_table': 'proposals',
                'ordering': ['-created_at'],
            },
        ),
    ]
