apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd  # Replace with the namespace where Argo CD is installed
type: Opaque
stringData:
  server.secretkey: "Yd/k4euHxNJkJ+/7r5x38+Fn8RrRS001XHUFJGDUra0="  # Replace with a secure random string
  webhook.github.secret: "your-github-webhook-secret"  # Optional
  # oidc.keycloak.clientSecret: "your-keycloak-client-secret"  # Optional