apiVersion: v1
kind: PersistentVolume
metadata:
  name: kmlflow-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  hostPath:
    path: /home/namedprofile/Code/kmlflow/volume  # This should be the same directory you mounted in the kind cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data
spec:
  volumeName: kmlflow-data  # Ensure the volumeName matches the PV name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
