apiVersion: v1
kind: PersistentVolume
metadata:
  name: kmlflow-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  hostPath:
    path: /data  # This should be the same directory you mounted in the kind cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data
spec:
  volumeName: kmlflow-data  # Ensure the volumeName matches the PV name
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
