apiVersion: v1
kind: PersistentVolume
metadata:
  name: kmlflow-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  hostPath:
    path: /data/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data
spec:
  volumeName: mlflow-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
