apiVersion: v1
kind: PersistentVolume
metadata:
  name: katib-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /data/katib  # This should be the same directory you mounted in the kind cluster
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kfp-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /data/kfp  # This should be the same directory you mounted in the kind cluster
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: kubeflow
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /data/kfp  # This should be the same directory you mounted in the kind cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv
  namespace: kubeflow
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katib-data
  namespace: kubeflow
spec:
  storageClassName: standard
  volumeName: katib-data  # Ensure the volumeName matches the PV name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kfp-pv
  namespace: kubeflow
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi