name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs on push to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build ./example -f ./examples/docker/Dockerfile.fit -t pytorch-train-gpu

      - name: Tag Docker image
        run: |
          docker tag pytorch-train-gpu akinolawilson/pytorch-train-gpu:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push akinolawilson/pytorch-train-gpu:latest

